services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/fittrack
      - JWT_ACCESS_SECRET=dev_access_secret
      - JWT_REFRESH_SECRET=dev_refresh_secret
      - ACCESS_TOKEN_EXPIRES=15m
      - REFRESH_TOKEN_EXPIRES=7d
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo

volumes:
  mongo-data:
